spring.datasource.url=jdbc:postgresql://aws-1-ap-south-1.pooler.supabase.com:6543/postgres?sslmode=require&prepareThreshold=0&pgbouncer=true
spring.datasource.username=postgres.rarizpparzyaicxkitvb
spring.datasource.password=jumbwatch123Hexa

# Force the dialect since Hibernate is struggling to "auto-detect" it without a successful login
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none

# Hikari specific setting for the pooler
spring.datasource.hikari.data-source-properties.prepareThreshold=0
spring.datasource.hikari.maximum-pool-size=2